{
  "provider": {
    "name": "clickup"
  },
  "data_sources": {
    "authorized_user": {
      "read": {
        "path": "/v2/user",
        "method": "get"
      },
      "schema": {}
    },
    "authorized_teams": {
      "read": {
        "path": "/v2/team",
        "method": "get"
      },
      "schema": {}
    },
    "task_comments": {
      "read": {
        "path": "/v2/task/{task_id}/comment",
        "method": "get"
      },
      "schema": {}
    },
    "chat_view_comments": {
      "read": {
        "path": "/v2/view/{view_id}/comment",
        "method": "get"
      },
      "schema": {}
    },
    "list_comments": {
      "read": {
        "path": "/v2/list/{list_id}/comment",
        "method": "get"
      },
      "schema": {}
    },
    "threaded_comments": {
      "read": {
        "path": "/v2/comment/{comment_id}/reply",
        "method": "get"
      },
      "schema": {}
    },
    "accessible_custom_fields": {
      "read": {
        "path": "/v2/list/{list_id}/field",
        "method": "get"
      },
      "schema": {}
    },
    "folder_available_fields": {
      "read": {
        "path": "/v2/folder/{folder_id}/field",
        "method": "get"
      },
      "schema": {}
    },
    "space_available_fields": {
      "read": {
        "path": "/v2/space/{space_id}/field",
        "method": "get"
      },
      "schema": {}
    },
    "team_available_fields": {
      "read": {
        "path": "/v2/team/{team_id}/field",
        "method": "get"
      },
      "schema": {}
    },
    "folders": {
      "read": {
        "path": "/v2/space/{space_id}/folder",
        "method": "get"
      },
      "schema": {}
    },
    "goal": {
      "read": {
        "path": "/v2/goal/{goal_id}",
        "method": "get"
      },
      "schema": {}
    },
    "guest": {
      "read": {
        "path": "/v2/team/{team_id}/guest/{guest_id}",
        "method": "get"
      },
      "schema": {}
    },
    "lists": {
      "read": {
        "path": "/v2/folder/{folder_id}/list",
        "method": "get"
      },
      "schema": {}
    },
    "folderless_lists": {
      "read": {
        "path": "/v2/space/{space_id}/list",
        "method": "get"
      },
      "schema": {}
    },
    "list": {
      "read": {
        "path": "/v2/list/{list_id}",
        "method": "get"
      },
      "schema": {}
    },
    "task_members": {
      "read": {
        "path": "/v2/task/{task_id}/member",
        "method": "get"
      },
      "schema": {}
    },
    "list_members": {
      "read": {
        "path": "/v2/list/{list_id}/member",
        "method": "get"
      },
      "schema": {}
    },
    "custom_roles": {
      "read": {
        "path": "/v2/team/{team_id}/customroles",
        "method": "get"
      },
      "schema": {}
    },
    "shared_hierarchy": {
      "read": {
        "path": "/v2/team/{team_id}/shared",
        "method": "get"
      },
      "schema": {}
    },
    "spaces": {
      "read": {
        "path": "/v2/team/{team_id}/space",
        "method": "get"
      },
      "schema": {}
    },
    "space": {
      "read": {
        "path": "/v2/space/{space_id}",
        "method": "get"
      },
      "schema": {}
    },
    "space_tags": {
      "read": {
        "path": "/v2/space/{space_id}/tag",
        "method": "get"
      },
      "schema": {}
    },
    "tasks": {
      "read": {
        "path": "/v2/list/{list_id}/task",
        "method": "get"
      },
      "schema": {}
    },
    "filtered_team_tasks": {
      "read": {
        "path": "/v2/team/{team_id}/task",
        "method": "get"
      },
      "schema": {}
    },
    "task_templates": {
      "read": {
        "path": "/v2/team/{team_id}/taskTemplate",
        "method": "get"
      },
      "schema": {}
    },
    "list_templates": {
      "read": {
        "path": "/v2/team/{team_id}/list_template",
        "method": "get"
      },
      "schema": {}
    },
    "folder_templates": {
      "read": {
        "path": "/v2/team/{team_id}/folder_template",
        "method": "get"
      },
      "schema": {}
    },
    "workspace_seats": {
      "read": {
        "path": "/v2/team/{team_id}/seats",
        "method": "get"
      },
      "schema": {}
    },
    "workspace_plan": {
      "read": {
        "path": "/v2/team/{team_id}/plan",
        "method": "get"
      },
      "schema": {}
    },
    "custom_items": {
      "read": {
        "path": "/v2/team/{team_id}/custom_item",
        "method": "get"
      },
      "schema": {}
    },
    "user_groups": {
      "read": {
        "path": "/v2/group",
        "method": "get"
      },
      "schema": {}
    },
    "tracked_time": {
      "read": {
        "path": "/v2/task/{task_id}/time",
        "method": "get"
      },
      "schema": {}
    },
    "time_entry": {
      "read": {
        "path": "/v2/team/{team_id}/time_entries/{timer_id}",
        "method": "get"
      },
      "schema": {}
    },
    "time_entry_history": {
      "read": {
        "path": "/v2/team/{team_id}/time_entries/{timer_id}/history",
        "method": "get"
      },
      "schema": {}
    },
    "running_time_entry": {
      "read": {
        "path": "/v2/team/{team_id}/time_entries/current",
        "method": "get"
      },
      "schema": {}
    },
    "time_entry_tags": {
      "read": {
        "path": "/v2/team/{team_id}/time_entries/tags",
        "method": "get"
      },
      "schema": {}
    },
    "user": {
      "read": {
        "path": "/v2/team/{team_id}/user/{user_id}",
        "method": "get"
      },
      "schema": {}
    },
    "team_views": {
      "read": {
        "path": "/v2/team/{team_id}/view",
        "method": "get"
      },
      "schema": {}
    },
    "space_views": {
      "read": {
        "path": "/v2/space/{space_id}/view",
        "method": "get"
      },
      "schema": {}
    },
    "folder_views": {
      "read": {
        "path": "/v2/folder/{folder_id}/view",
        "method": "get"
      },
      "schema": {}
    },
    "list_views": {
      "read": {
        "path": "/v2/list/{list_id}/view",
        "method": "get"
      },
      "schema": {}
    },
    "webhooks": {
      "read": {
        "path": "/v2/team/{team_id}/webhook",
        "method": "get"
      },
      "schema": {}
    }
  },
  "resources": {
    "goal": {
      "create": {
        "path": "/v2/team/{team_id}/goal",
        "method": "post"
      },
      "read": {
        "path": "/v2/goal/{goal_id}",
        "method": "get"
      },
      "update": {
        "path": "/v2/goal/{goal_id}",
        "method": "put"
      },
      "delete": {
        "path": "/v2/goal/{goal_id}",
        "method": "delete"
      },
      "schema": {}
    },
    "list": {
      "create": {
        "path": "/v2/folder/{folder_id}/list",
        "method": "post"
      },
      "read": {
        "path": "/v2/list/{list_id}",
        "method": "get"
      },
      "update": {
        "path": "/v2/list/{list_id}",
        "method": "put"
      },
      "delete": {
        "path": "/v2/list/{list_id}",
        "method": "delete"
      },
      "schema": {}
    },
    "space": {
      "create": {
        "path": "/v2/team/{team_id}/space",
        "method": "post"
      },
      "read": {
        "path": "/v2/space/{space_id}",
        "method": "get"
      },
      "update": {
        "path": "/v2/space/{space_id}",
        "method": "put"
      },
      "delete": {
        "path": "/v2/space/{space_id}",
        "method": "delete"
      },
      "schema": {}
    },
    "task": {
      "create": {
        "path": "/v2/list/{list_id}/task",
        "method": "post"
      },
      "read": {
        "path": "/v2/task/{task_id}",
        "method": "get"
      },
      "update": {
        "path": "/v2/task/{task_id}",
        "method": "put"
      },
      "delete": {
        "path": "/v2/task/{task_id}",
        "method": "delete"
      },
      "schema": {}
    },
    "folderless_list": {
      "create": {
        "path": "/v2/space/{space_id}/list",
        "method": "post"
      },
      "read": {
        "path": "/v2/list/{list_id}",
        "method": "get"
      },
      "update": {
        "path": "/v2/list/{list_id}",
        "method": "put"
      },
      "delete": {
        "path": "/v2/list/{list_id}",
        "method": "delete"
      },
      "schema": {}
    }
  }
}