// Code generated by ogen, DO NOT EDIT.

package clickupv3

import (
	"context"

	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateChatChannel implements createChatChannel operation.
//
// This endpoint creates a new Channel not tied to a Space, Folder, or List. If a Channel with the
// specified name already exists it returns it.
//
// POST /api/v3/workspaces/{workspace_id}/chat/channels
func (UnimplementedHandler) CreateChatChannel(ctx context.Context, req *ChatCreateChatChannel, params CreateChatChannelParams) (r CreateChatChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateChatMessage implements createChatMessage operation.
//
// This endpoint creates a top level message.
//
// POST /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/messages
func (UnimplementedHandler) CreateChatMessage(ctx context.Context, req *CommentCreateChatMessage, params CreateChatMessageParams) (r CreateChatMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateChatReaction implements createChatReaction operation.
//
// This endpoint creates a message reaction using lower case emoji names.
//
// POST /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions
func (UnimplementedHandler) CreateChatReaction(ctx context.Context, req *CommentCreateChatReaction, params CreateChatReactionParams) (r CreateChatReactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDirectMessageChatChannel implements createDirectMessageChatChannel operation.
//
// This endpoint creates a new Direct Message between up to 15 users. If a Direct Message between those
// users already exists it returns it.
//
// POST /api/v3/workspaces/{workspace_id}/chat/channels/direct_message
func (UnimplementedHandler) CreateDirectMessageChatChannel(ctx context.Context, req *ChatCreateDirectMessageChatChannel, params CreateDirectMessageChatChannelParams) (r CreateDirectMessageChatChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDocPublic implements createDocPublic operation.
//
// Create a new Doc.
//
// POST /api/v3/workspaces/{workspace_id}/docs
func (UnimplementedHandler) CreateDocPublic(ctx context.Context, req *PublicDocsCreateDocOptionsDto, params CreateDocPublicParams) (r *PublicDocsDocDto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateLocationChatChannel implements createLocationChatChannel operation.
//
// This endpoint creates a Channel on a Space, Folder, or List. When a Channel already exists on the
// requested location, it returns it.
//
// POST /api/v3/workspaces/{workspace_id}/chat/channels/location
func (UnimplementedHandler) CreateLocationChatChannel(ctx context.Context, req *ChatCreateLocationChatChannel, params CreateLocationChatChannelParams) (r CreateLocationChatChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePagePublic implements createPagePublic operation.
//
// Create a page in a Doc.
//
// POST /api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages
func (UnimplementedHandler) CreatePagePublic(ctx context.Context, req *PublicDocsPublicCreatePageOptionsDto, params CreatePagePublicParams) (r *PublicDocsPageV3Dto, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateReplyMessage implements createReplyMessage operation.
//
// This endpoint creates a reply message.
//
// POST /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/replies
func (UnimplementedHandler) CreateReplyMessage(ctx context.Context, req *CommentCreateChatMessage, params CreateReplyMessageParams) (r CreateReplyMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteChatChannel implements deleteChatChannel operation.
//
// This endpoint deletes a Channel. Applies to Channels tied to a Space, Folder, or List or not tied to
// locations.
//
// DELETE /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}
func (UnimplementedHandler) DeleteChatChannel(ctx context.Context, params DeleteChatChannelParams) (r DeleteChatChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteChatMessage implements deleteChatMessage operation.
//
// This endpoint deletes a message.
//
// DELETE /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}
func (UnimplementedHandler) DeleteChatMessage(ctx context.Context, params DeleteChatMessageParams) (r DeleteChatMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteChatReaction implements deleteChatReaction operation.
//
// This endpoint deletes a message reaction.
//
// DELETE /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions/{reaction}
func (UnimplementedHandler) DeleteChatReaction(ctx context.Context, params DeleteChatReactionParams) (r DeleteChatReactionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditPagePublic implements editPagePublic operation.
//
// Edit a page in a Doc.
//
// PUT /api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages/{page_id}
func (UnimplementedHandler) EditPagePublic(ctx context.Context, req *PublicDocsPublicEditPageOptionsDto, params EditPagePublicParams) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatChannel implements getChatChannel operation.
//
// This endpoint retrieves a specific Channel given its ID.
//
// GET /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}
func (UnimplementedHandler) GetChatChannel(ctx context.Context, params GetChatChannelParams) (r GetChatChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatChannelFollowers implements getChatChannelFollowers operation.
//
// This endpoint retrieves followers of a specific Channel given its ID.
//
// GET /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/followers
func (UnimplementedHandler) GetChatChannelFollowers(ctx context.Context, params GetChatChannelFollowersParams) (r GetChatChannelFollowersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatChannelMembers implements getChatChannelMembers operation.
//
// This endpoint retrieves members of a specific Channel given its ID.
//
// GET /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/members
func (UnimplementedHandler) GetChatChannelMembers(ctx context.Context, params GetChatChannelMembersParams) (r GetChatChannelMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatChannels implements getChatChannels operation.
//
// This endpoint retrieves the Channels in a Workspace.
//
// GET /api/v3/workspaces/{workspace_id}/chat/channels
func (UnimplementedHandler) GetChatChannels(ctx context.Context, params GetChatChannelsParams) (r GetChatChannelsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatMessageReactions implements getChatMessageReactions operation.
//
// This endpoint retrieves the reactions to a message.
//
// GET /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions
func (UnimplementedHandler) GetChatMessageReactions(ctx context.Context, params GetChatMessageReactionsParams) (r GetChatMessageReactionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatMessageReplies implements getChatMessageReplies operation.
//
// This endpoint retrieves the replies to a message.
//
// GET /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/replies
func (UnimplementedHandler) GetChatMessageReplies(ctx context.Context, params GetChatMessageRepliesParams) (r GetChatMessageRepliesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatMessageTaggedUsers implements getChatMessageTaggedUsers operation.
//
// This endpoint retrieves tagged users for a message.
//
// GET /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/tagged_users
func (UnimplementedHandler) GetChatMessageTaggedUsers(ctx context.Context, params GetChatMessageTaggedUsersParams) (r GetChatMessageTaggedUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatMessages implements getChatMessages operation.
//
// This endpoint retrieves messages for a specified Channel.
//
// GET /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/messages
func (UnimplementedHandler) GetChatMessages(ctx context.Context, params GetChatMessagesParams) (r GetChatMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocPageListingPublic implements getDocPageListingPublic operation.
//
// View the PageListing for a Doc.
//
// GET /api/v3/workspaces/{workspace_id}/docs/{doc_id}/page_listing
func (UnimplementedHandler) GetDocPageListingPublic(ctx context.Context, params GetDocPageListingPublicParams) (r GetDocPageListingPublicRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocPagesPublic implements getDocPagesPublic operation.
//
// View the pages belonging to a Doc.
//
// GET /api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages
func (UnimplementedHandler) GetDocPagesPublic(ctx context.Context, params GetDocPagesPublicParams) (r PublicDocsGetDocPagesPublic200Response, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocPublic implements getDocPublic operation.
//
// View information about a Doc.
//
// GET /api/v3/workspaces/{workspace_id}/docs/{doc_id}
func (UnimplementedHandler) GetDocPublic(ctx context.Context, params GetDocPublicParams) (r GetDocPublicRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPagePublic implements getPagePublic operation.
//
// View the information about a page in a Doc. Due to markdown format limitations, some content
// elements [will not be displayed exactly as they appear in ClickUp].
//
// [will not be displayed exactly as they appear in ClickUp]: doc:docsimportexportlimitations/
//
// GET /api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages/{page_id}
func (UnimplementedHandler) GetPagePublic(ctx context.Context, params GetPagePublicParams) (r GetPagePublicRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetParentEntityAttachments implements getParentEntityAttachments operation.
//
// Return a list of attachments for the specified entity, including a task or File type Custom Field.
//
// GET /api/v3/workspaces/{workspace_id}/{entity_type}/{entity_id}/attachments
func (UnimplementedHandler) GetParentEntityAttachments(ctx context.Context, params GetParentEntityAttachmentsParams) (r GetParentEntityAttachmentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubtypes implements getSubtypes operation.
//
// Get the ID of each post subtype (Announcement, Discussion, Idea, and Update) for your Workspace, to
// use when [sending a message] with `type: post`. Subtype IDs are unique to each Workspace.
//
// GET /api/v3/workspaces/{workspace_id}/comments/types/{comment_type}/subtypes
//
// [sending a message]: https://developer.clickup.com/reference/createchatmessage
func (UnimplementedHandler) GetSubtypes(ctx context.Context, params GetSubtypesParams) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// MoveTask implements moveTask operation.
//
// Move a task to a new List. For Tasks in Multiple Lists, this endpoint only moves the task to a new
// home List.
//
// [Learn more] about the options available when moving a task to a new List.
//
// [Learn more]: doc:move-a-task-to-a-new-list
//
// PUT /api/v3/workspaces/{workspace_id}/tasks/{task_id}/home_list/{list_id}
func (UnimplementedHandler) MoveTask(ctx context.Context, req *TaskMoveTaskBodyParamsDto, params MoveTaskParams) (r MoveTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchChatMessage implements patchChatMessage operation.
//
// This endpoint updates a message.
//
// PATCH /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}
func (UnimplementedHandler) PatchChatMessage(ctx context.Context, req *CommentPatchChatMessage, params PatchChatMessageParams) (r PatchChatMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostEntityAttachment implements postEntityAttachment operation.
//
// Upload an attachment to a task or to a file type Custom Field. Once a file has been uploaded to a
// `custom_fields` entity, use [Set Custom Field Value] to associate the uploaded file with a task. To
// retrieve the ID of a Custom Field, you can use [Get List Custom Fields] or [Get task].
//
// [Set Custom Field Value]: ref:SetCustomFieldValue
// [Get List Custom Fields]: red:GetAccessibleCustomFields
// [Get task]: ref:GetTask
//
// POST /api/v3/workspaces/{workspace_id}/{entity_type}/{entity_id}/attachments
func (UnimplementedHandler) PostEntityAttachment(ctx context.Context, req *AttachmentsPublicPostAttachmentBodyParamsDtoMultipart, params PostEntityAttachmentParams) (r PostEntityAttachmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PublicPatchAcl implements publicPatchAcl operation.
//
// Update the privacy and access settings of an object or location in the Workspace. Note that sharing
// an item may incur charges.
//
// PATCH /api/v3/workspaces/{workspace_id}/{object_type}/{object_id}/acls
func (UnimplementedHandler) PublicPatchAcl(ctx context.Context, req *UserPatchAclApiRequest, params PublicPatchAclParams) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// QueryAuditLog implements queryAuditLog operation.
//
// Create Workspace-level audit logs. Only the Workspace owner can create audit logs. Note: This
// endpoint is only available to Workspaces on our [Enterprise Plan].
//
// POST /api/v3/workspaces/{workspace_id}/auditlogs
//
// [Enterprise Plan]: https://clickup.com/pricing
func (UnimplementedHandler) QueryAuditLog(ctx context.Context, req *AutoAuditlogAuditLogQueryRequest, params QueryAuditLogParams) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplaceTimeEstimatesByUser implements replaceTimeEstimatesByUser operation.
//
// Replaces all time estimates for a task with the provided time estimates. Any existing time estimates
// not included in the request will be removed.
//
// Assignees must be currently assigned to the task, or use `assignee: unassigned` to set a time
// estimates for unassigned work.
//
// You can set up to 10 estimates per request.
//
// Note: This endpoint is only available on our Business Plan or above.
//
// PUT /api/v3/workspaces/{workspace_id}/tasks/{task_id}/time_estimates_by_user
func (UnimplementedHandler) ReplaceTimeEstimatesByUser(ctx context.Context, req TaskPublicApiTaskControllerReplaceTimeEstimatesByUserRequest, params ReplaceTimeEstimatesByUserParams) (r ReplaceTimeEstimatesByUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchDocsPublic implements searchDocsPublic operation.
//
// View the Docs in your Workspace. You can only view information of Docs you can access.
//
// GET /api/v3/workspaces/{workspace_id}/docs
func (UnimplementedHandler) SearchDocsPublic(ctx context.Context, params SearchDocsPublicParams) (r *PublicDocsDocsSearchResultDto, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateChatChannel implements updateChatChannel operation.
//
// This endpoint updates a single Channel.
//
// PATCH /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}
func (UnimplementedHandler) UpdateChatChannel(ctx context.Context, req *ChatUpdateChatChannel, params UpdateChatChannelParams) (r UpdateChatChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTimeEstimatesByUser implements updateTimeEstimatesByUser operation.
//
// Replace the time estimates on a task for specified assignees.
//
// Assignees must be currently assigned to the task, or use `assignee: unassigned` to set a time
// estimates for unassigned work.
//
// You can set up to 10 estimates per request.
//
// Note: This endpoint is only available on our Business Plan or above.
//
// PATCH /api/v3/workspaces/{workspace_id}/tasks/{task_id}/time_estimates_by_user
func (UnimplementedHandler) UpdateTimeEstimatesByUser(ctx context.Context, req TaskPublicApiTaskControllerUpdateTimeEstimatesByUserRequest, params UpdateTimeEstimatesByUserParams) (r UpdateTimeEstimatesByUserRes, _ error) {
	return r, ht.ErrNotImplemented
}
