// Code generated by ogen, DO NOT EDIT.

package clickupv3

// setDefaults set default value of fields.
func (s *ChatUpdateChatChannel) setDefaults() {
	{
		val := ChatUpdateChatChannelContentFormat("text/md")
		s.ContentFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CommentCreateChatMessage) setDefaults() {
	{
		val := CommentCreateChatMessageContentFormat("text/md")
		s.ContentFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CommentPatchChatMessage) setDefaults() {
	{
		val := CommentPatchChatMessageContentFormat("text/md")
		s.ContentFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PublicDocsCreateDocOptionsDto) setDefaults() {
	{
		val := string("")
		s.Name.SetTo(val)
	}
	{
	}
	{
		val := bool(true)
		s.CreatePage.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PublicDocsPublicCreatePageOptionsDto) setDefaults() {
	{
		val := string("")
		s.Name.SetTo(val)
	}
	{
		val := string("")
		s.Content.SetTo(val)
	}
	{
		val := PublicDocsPublicCreatePageOptionsDtoContentFormat("text/md")
		s.ContentFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PublicDocsPublicEditPageOptionsDto) setDefaults() {
	{
		val := string("")
		s.Name.SetTo(val)
	}
	{
		val := string("")
		s.Content.SetTo(val)
	}
	{
		val := PublicDocsPublicEditPageOptionsDtoContentEditMode("replace")
		s.ContentEditMode.SetTo(val)
	}
	{
		val := PublicDocsPublicEditPageOptionsDtoContentFormat("text/md")
		s.ContentFormat.SetTo(val)
	}
}
