// Code generated by ogen, DO NOT EDIT.

package clickupv3

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn46AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn3AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn11AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn14AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn5AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
		"PATCH":  "Authorization,Content-Type",
	}
	rn25AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn27AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn6AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn9AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"PATCH":  "Authorization,Content-Type",
	}
	rn10AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn21AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
	}
	rn19AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn29AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn39AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn13AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn16AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn31AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn17AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn23AllowedHeaders = map[string]string{
		"GET": "Authorization",
		"PUT": "Authorization,Content-Type",
	}
	rn43AllowedHeaders = map[string]string{
		"PUT": "Authorization,Content-Type",
	}
	rn48AllowedHeaders = map[string]string{
		"PATCH": "Authorization,Content-Type",
		"PUT":   "Authorization,Content-Type",
	}
	rn45AllowedHeaders = map[string]string{
		"PATCH": "Authorization,Content-Type",
	}
	rn35AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [3]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v3/workspaces/"

			if l := len("/api/v3/workspaces/"); len(elem) >= l && elem[0:l] == "/api/v3/workspaces/" {
				elem = elem[l:]
			} else {
				break
			}

			// Param: "workspace_id"
			// Match until "/"
			idx := strings.IndexByte(elem, '/')
			if idx < 0 {
				idx = len(elem)
			}
			args[0] = elem[:idx]
			elem = elem[idx:]

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "auditlogs"
					origElem := elem
					if l := len("auditlogs"); len(elem) >= l && elem[0:l] == "auditlogs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleQueryAuditLogRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn46AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}

					elem = origElem
				case 'c': // Prefix: "c"
					origElem := elem
					if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'h': // Prefix: "hat/"

						if l := len("hat/"); len(elem) >= l && elem[0:l] == "hat/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "channels"

							if l := len("channels"); len(elem) >= l && elem[0:l] == "channels" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleGetChatChannelsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateChatChannelRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn3AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'd': // Prefix: "direct_message"
									origElem := elem
									if l := len("direct_message"); len(elem) >= l && elem[0:l] == "direct_message" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleCreateDirectMessageChatChannelRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn11AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

									elem = origElem
								case 'l': // Prefix: "location"
									origElem := elem
									if l := len("location"); len(elem) >= l && elem[0:l] == "location" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleCreateLocationChatChannelRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn14AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

									elem = origElem
								}
								// Param: "channel_id"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch r.Method {
									case "DELETE":
										s.handleDeleteChatChannelRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetChatChannelRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "PATCH":
										s.handleUpdateChatChannelRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE,GET,PATCH",
											allowedHeaders: rn5AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "application/json",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'f': // Prefix: "followers"

										if l := len("followers"); len(elem) >= l && elem[0:l] == "followers" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleGetChatChannelFollowersRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: rn25AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									case 'm': // Prefix: "me"

										if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'm': // Prefix: "mbers"

											if l := len("mbers"); len(elem) >= l && elem[0:l] == "mbers" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "GET":
													s.handleGetChatChannelMembersRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "GET",
														allowedHeaders: rn27AllowedHeaders,
														acceptPost:     "",
														acceptPatch:    "",
													})
												}

												return
											}

										case 's': // Prefix: "ssages"

											if l := len("ssages"); len(elem) >= l && elem[0:l] == "ssages" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "GET":
													s.handleGetChatMessagesRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												case "POST":
													s.handleCreateChatMessageRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "GET,POST",
														allowedHeaders: rn6AllowedHeaders,
														acceptPost:     "application/json",
														acceptPatch:    "",
													})
												}

												return
											}

										}

									}

								}

							}

						case 'm': // Prefix: "messages/"

							if l := len("messages/"); len(elem) >= l && elem[0:l] == "messages/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "message_id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleDeleteChatMessageRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "PATCH":
									s.handlePatchChatMessageRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,PATCH",
										allowedHeaders: rn9AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'r': // Prefix: "re"

									if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'a': // Prefix: "actions"

										if l := len("actions"); len(elem) >= l && elem[0:l] == "actions" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch r.Method {
											case "GET":
												s.handleGetChatMessageReactionsRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											case "POST":
												s.handleCreateChatReactionRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET,POST",
													allowedHeaders: rn10AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "reaction"
											// Leaf parameter, slashes are prohibited
											idx := strings.IndexByte(elem, '/')
											if idx >= 0 {
												break
											}
											args[2] = elem
											elem = ""

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "DELETE":
													s.handleDeleteChatReactionRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "DELETE",
														allowedHeaders: rn21AllowedHeaders,
														acceptPost:     "",
														acceptPatch:    "",
													})
												}

												return
											}

										}

									case 'p': // Prefix: "plies"

										if l := len("plies"); len(elem) >= l && elem[0:l] == "plies" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleGetChatMessageRepliesRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											case "POST":
												s.handleCreateReplyMessageRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET,POST",
													allowedHeaders: rn19AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								case 't': // Prefix: "tagged_users"

									if l := len("tagged_users"); len(elem) >= l && elem[0:l] == "tagged_users" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleGetChatMessageTaggedUsersRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn29AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						}

					case 'o': // Prefix: "omments/types/"

						if l := len("omments/types/"); len(elem) >= l && elem[0:l] == "omments/types/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "comment_type"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[1] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/subtypes"

							if l := len("/subtypes"); len(elem) >= l && elem[0:l] == "/subtypes" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetSubtypesRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn39AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

					elem = origElem
				case 'd': // Prefix: "docs"
					origElem := elem
					if l := len("docs"); len(elem) >= l && elem[0:l] == "docs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleSearchDocsPublicRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "POST":
							s.handleCreateDocPublicRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn13AllowedHeaders,
								acceptPost:     "application/json",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "doc_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[1] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetDocPublicRequest([2]string{
									args[0],
									args[1],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn16AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/page"

							if l := len("/page"); len(elem) >= l && elem[0:l] == "/page" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case '_': // Prefix: "_listing"

								if l := len("_listing"); len(elem) >= l && elem[0:l] == "_listing" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetDocPageListingPublicRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn31AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleGetDocPagesPublicRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleCreatePagePublicRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn17AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "page_id"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[2] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleGetPagePublicRequest([3]string{
												args[0],
												args[1],
												args[2],
											}, elemIsEscaped, w, r)
										case "PUT":
											s.handleEditPagePublicRequest([3]string{
												args[0],
												args[1],
												args[2],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET,PUT",
												allowedHeaders: rn23AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						}

					}

					elem = origElem
				case 't': // Prefix: "tasks/"
					origElem := elem
					if l := len("tasks/"); len(elem) >= l && elem[0:l] == "tasks/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "task_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[1] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'h': // Prefix: "home_list/"

							if l := len("home_list/"); len(elem) >= l && elem[0:l] == "home_list/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "list_id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[2] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PUT":
									s.handleMoveTaskRequest([3]string{
										args[0],
										args[1],
										args[2],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PUT",
										allowedHeaders: rn43AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 't': // Prefix: "time_estimates_by_user"

							if l := len("time_estimates_by_user"); len(elem) >= l && elem[0:l] == "time_estimates_by_user" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PATCH":
									s.handleUpdateTimeEstimatesByUserRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleReplaceTimeEstimatesByUserRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PATCH,PUT",
										allowedHeaders: rn48AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}

						}

					}

					elem = origElem
				}
				// Param: "entity_type"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[1] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "entity_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[2] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/a"

						if l := len("/a"); len(elem) >= l && elem[0:l] == "/a" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "cls"

							if l := len("cls"); len(elem) >= l && elem[0:l] == "cls" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PATCH":
									s.handlePublicPatchAclRequest([3]string{
										args[0],
										args[1],
										args[2],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PATCH",
										allowedHeaders: rn45AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}

						case 't': // Prefix: "ttachments"

							if l := len("ttachments"); len(elem) >= l && elem[0:l] == "ttachments" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetParentEntityAttachmentsRequest([3]string{
										args[0],
										args[1],
										args[2],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handlePostEntityAttachmentRequest([3]string{
										args[0],
										args[1],
										args[2],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn35AllowedHeaders,
										acceptPost:     "multipart/form-data",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [3]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/api/v3/workspaces/"

			if l := len("/api/v3/workspaces/"); len(elem) >= l && elem[0:l] == "/api/v3/workspaces/" {
				elem = elem[l:]
			} else {
				break
			}

			// Param: "workspace_id"
			// Match until "/"
			idx := strings.IndexByte(elem, '/')
			if idx < 0 {
				idx = len(elem)
			}
			args[0] = elem[:idx]
			elem = elem[idx:]

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "auditlogs"
					origElem := elem
					if l := len("auditlogs"); len(elem) >= l && elem[0:l] == "auditlogs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = QueryAuditLogOperation
							r.summary = "Create Workspace-level audit logs"
							r.operationID = "queryAuditLog"
							r.operationGroup = ""
							r.pathPattern = "/api/v3/workspaces/{workspace_id}/auditlogs"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

					elem = origElem
				case 'c': // Prefix: "c"
					origElem := elem
					if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'h': // Prefix: "hat/"

						if l := len("hat/"); len(elem) >= l && elem[0:l] == "hat/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "channels"

							if l := len("channels"); len(elem) >= l && elem[0:l] == "channels" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = GetChatChannelsOperation
									r.summary = "Retrieve Channels"
									r.operationID = "getChatChannels"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreateChatChannelOperation
									r.summary = "Create a Channel"
									r.operationID = "createChatChannel"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'd': // Prefix: "direct_message"
									origElem := elem
									if l := len("direct_message"); len(elem) >= l && elem[0:l] == "direct_message" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = CreateDirectMessageChatChannelOperation
											r.summary = "Create a Direct Message"
											r.operationID = "createDirectMessageChatChannel"
											r.operationGroup = ""
											r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/direct_message"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

									elem = origElem
								case 'l': // Prefix: "location"
									origElem := elem
									if l := len("location"); len(elem) >= l && elem[0:l] == "location" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = CreateLocationChatChannelOperation
											r.summary = "Create a Channel on a Space, Folder, or List"
											r.operationID = "createLocationChatChannel"
											r.operationGroup = ""
											r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/location"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

									elem = origElem
								}
								// Param: "channel_id"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch method {
									case "DELETE":
										r.name = DeleteChatChannelOperation
										r.summary = "Delete a Channel"
										r.operationID = "deleteChatChannel"
										r.operationGroup = ""
										r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}"
										r.args = args
										r.count = 2
										return r, true
									case "GET":
										r.name = GetChatChannelOperation
										r.summary = "Retrieve a Channel"
										r.operationID = "getChatChannel"
										r.operationGroup = ""
										r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}"
										r.args = args
										r.count = 2
										return r, true
									case "PATCH":
										r.name = UpdateChatChannelOperation
										r.summary = "Update a Channel"
										r.operationID = "updateChatChannel"
										r.operationGroup = ""
										r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'f': // Prefix: "followers"

										if l := len("followers"); len(elem) >= l && elem[0:l] == "followers" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = GetChatChannelFollowersOperation
												r.summary = "Retrieve Channel followers"
												r.operationID = "getChatChannelFollowers"
												r.operationGroup = ""
												r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/followers"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									case 'm': // Prefix: "me"

										if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'm': // Prefix: "mbers"

											if l := len("mbers"); len(elem) >= l && elem[0:l] == "mbers" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "GET":
													r.name = GetChatChannelMembersOperation
													r.summary = "Retrieve Channel members"
													r.operationID = "getChatChannelMembers"
													r.operationGroup = ""
													r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/members"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

										case 's': // Prefix: "ssages"

											if l := len("ssages"); len(elem) >= l && elem[0:l] == "ssages" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "GET":
													r.name = GetChatMessagesOperation
													r.summary = "Retrieve Channel messages"
													r.operationID = "getChatMessages"
													r.operationGroup = ""
													r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/messages"
													r.args = args
													r.count = 2
													return r, true
												case "POST":
													r.name = CreateChatMessageOperation
													r.summary = "Send a message"
													r.operationID = "createChatMessage"
													r.operationGroup = ""
													r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/messages"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

										}

									}

								}

							}

						case 'm': // Prefix: "messages/"

							if l := len("messages/"); len(elem) >= l && elem[0:l] == "messages/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "message_id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = DeleteChatMessageOperation
									r.summary = "Delete a message"
									r.operationID = "deleteChatMessage"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}"
									r.args = args
									r.count = 2
									return r, true
								case "PATCH":
									r.name = PatchChatMessageOperation
									r.summary = "Update a message"
									r.operationID = "patchChatMessage"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'r': // Prefix: "re"

									if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'a': // Prefix: "actions"

										if l := len("actions"); len(elem) >= l && elem[0:l] == "actions" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch method {
											case "GET":
												r.name = GetChatMessageReactionsOperation
												r.summary = "Retrieve message reactions"
												r.operationID = "getChatMessageReactions"
												r.operationGroup = ""
												r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions"
												r.args = args
												r.count = 2
												return r, true
											case "POST":
												r.name = CreateChatReactionOperation
												r.summary = "Create a message reaction"
												r.operationID = "createChatReaction"
												r.operationGroup = ""
												r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "reaction"
											// Leaf parameter, slashes are prohibited
											idx := strings.IndexByte(elem, '/')
											if idx >= 0 {
												break
											}
											args[2] = elem
											elem = ""

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "DELETE":
													r.name = DeleteChatReactionOperation
													r.summary = "Delete a message reaction"
													r.operationID = "deleteChatReaction"
													r.operationGroup = ""
													r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions/{reaction}"
													r.args = args
													r.count = 3
													return r, true
												default:
													return
												}
											}

										}

									case 'p': // Prefix: "plies"

										if l := len("plies"); len(elem) >= l && elem[0:l] == "plies" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = GetChatMessageRepliesOperation
												r.summary = "Retrieve message replies"
												r.operationID = "getChatMessageReplies"
												r.operationGroup = ""
												r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/replies"
												r.args = args
												r.count = 2
												return r, true
											case "POST":
												r.name = CreateReplyMessageOperation
												r.summary = "Create a reply message"
												r.operationID = "createReplyMessage"
												r.operationGroup = ""
												r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/replies"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									}

								case 't': // Prefix: "tagged_users"

									if l := len("tagged_users"); len(elem) >= l && elem[0:l] == "tagged_users" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = GetChatMessageTaggedUsersOperation
											r.summary = "Retrieve message tagged users"
											r.operationID = "getChatMessageTaggedUsers"
											r.operationGroup = ""
											r.pathPattern = "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/tagged_users"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							}

						}

					case 'o': // Prefix: "omments/types/"

						if l := len("omments/types/"); len(elem) >= l && elem[0:l] == "omments/types/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "comment_type"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[1] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/subtypes"

							if l := len("/subtypes"); len(elem) >= l && elem[0:l] == "/subtypes" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetSubtypesOperation
									r.summary = "Get Post Subtype IDs"
									r.operationID = "getSubtypes"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/comments/types/{comment_type}/subtypes"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					}

					elem = origElem
				case 'd': // Prefix: "docs"
					origElem := elem
					if l := len("docs"); len(elem) >= l && elem[0:l] == "docs" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = SearchDocsPublicOperation
							r.summary = "Search for Docs"
							r.operationID = "searchDocsPublic"
							r.operationGroup = ""
							r.pathPattern = "/api/v3/workspaces/{workspace_id}/docs"
							r.args = args
							r.count = 1
							return r, true
						case "POST":
							r.name = CreateDocPublicOperation
							r.summary = "Create a Doc"
							r.operationID = "createDocPublic"
							r.operationGroup = ""
							r.pathPattern = "/api/v3/workspaces/{workspace_id}/docs"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "doc_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[1] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetDocPublicOperation
								r.summary = "Fetch a Doc"
								r.operationID = "getDocPublic"
								r.operationGroup = ""
								r.pathPattern = "/api/v3/workspaces/{workspace_id}/docs/{doc_id}"
								r.args = args
								r.count = 2
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/page"

							if l := len("/page"); len(elem) >= l && elem[0:l] == "/page" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case '_': // Prefix: "_listing"

								if l := len("_listing"); len(elem) >= l && elem[0:l] == "_listing" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetDocPageListingPublicOperation
										r.summary = "Fetch PageListing for a Doc"
										r.operationID = "getDocPageListingPublic"
										r.operationGroup = ""
										r.pathPattern = "/api/v3/workspaces/{workspace_id}/docs/{doc_id}/page_listing"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = GetDocPagesPublicOperation
										r.summary = "Fetch Pages belonging to a Doc"
										r.operationID = "getDocPagesPublic"
										r.operationGroup = ""
										r.pathPattern = "/api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages"
										r.args = args
										r.count = 2
										return r, true
									case "POST":
										r.name = CreatePagePublicOperation
										r.summary = "Create a Page"
										r.operationID = "createPagePublic"
										r.operationGroup = ""
										r.pathPattern = "/api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "page_id"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[2] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = GetPagePublicOperation
											r.summary = "Get page"
											r.operationID = "getPagePublic"
											r.operationGroup = ""
											r.pathPattern = "/api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages/{page_id}"
											r.args = args
											r.count = 3
											return r, true
										case "PUT":
											r.name = EditPagePublicOperation
											r.summary = "Edit a Page"
											r.operationID = "editPagePublic"
											r.operationGroup = ""
											r.pathPattern = "/api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages/{page_id}"
											r.args = args
											r.count = 3
											return r, true
										default:
											return
										}
									}

								}

							}

						}

					}

					elem = origElem
				case 't': // Prefix: "tasks/"
					origElem := elem
					if l := len("tasks/"); len(elem) >= l && elem[0:l] == "tasks/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "task_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[1] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'h': // Prefix: "home_list/"

							if l := len("home_list/"); len(elem) >= l && elem[0:l] == "home_list/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "list_id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[2] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PUT":
									r.name = MoveTaskOperation
									r.summary = "Move a task to a new List"
									r.operationID = "moveTask"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/tasks/{task_id}/home_list/{list_id}"
									r.args = args
									r.count = 3
									return r, true
								default:
									return
								}
							}

						case 't': // Prefix: "time_estimates_by_user"

							if l := len("time_estimates_by_user"); len(elem) >= l && elem[0:l] == "time_estimates_by_user" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PATCH":
									r.name = UpdateTimeEstimatesByUserOperation
									r.summary = "Update task time estimates by user"
									r.operationID = "updateTimeEstimatesByUser"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/tasks/{task_id}/time_estimates_by_user"
									r.args = args
									r.count = 2
									return r, true
								case "PUT":
									r.name = ReplaceTimeEstimatesByUserOperation
									r.summary = "Replace task time estimates"
									r.operationID = "replaceTimeEstimatesByUser"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/tasks/{task_id}/time_estimates_by_user"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					}

					elem = origElem
				}
				// Param: "entity_type"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[1] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "entity_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[2] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/a"

						if l := len("/a"); len(elem) >= l && elem[0:l] == "/a" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'c': // Prefix: "cls"

							if l := len("cls"); len(elem) >= l && elem[0:l] == "cls" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PATCH":
									r.name = PublicPatchAclOperation
									r.summary = "Update privacy and access of an object or location"
									r.operationID = "publicPatchAcl"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/{object_type}/{object_id}/acls"
									r.args = args
									r.count = 3
									return r, true
								default:
									return
								}
							}

						case 't': // Prefix: "ttachments"

							if l := len("ttachments"); len(elem) >= l && elem[0:l] == "ttachments" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetParentEntityAttachmentsOperation
									r.summary = "Get Attachments"
									r.operationID = "getParentEntityAttachments"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/{entity_type}/{entity_id}/attachments"
									r.args = args
									r.count = 3
									return r, true
								case "POST":
									r.name = PostEntityAttachmentOperation
									r.summary = "Create an Attachment"
									r.operationID = "postEntityAttachment"
									r.operationGroup = ""
									r.pathPattern = "/api/v3/workspaces/{workspace_id}/{entity_type}/{entity_id}/attachments"
									r.args = args
									r.count = 3
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			}

		}
	}
	return r, false
}
