// Code generated by ogen, DO NOT EDIT.

package clickupv3

import (
	"context"

	"github.com/go-faster/jx"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateChatChannel implements createChatChannel operation.
	//
	// This endpoint creates a new Channel not tied to a Space, Folder, or List. If a Channel with the
	// specified name already exists it returns it.
	//
	// POST /api/v3/workspaces/{workspace_id}/chat/channels
	CreateChatChannel(ctx context.Context, req *ChatCreateChatChannel, params CreateChatChannelParams) (CreateChatChannelRes, error)
	// CreateChatMessage implements createChatMessage operation.
	//
	// This endpoint creates a top level message.
	//
	// POST /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/messages
	CreateChatMessage(ctx context.Context, req *CommentCreateChatMessage, params CreateChatMessageParams) (CreateChatMessageRes, error)
	// CreateChatReaction implements createChatReaction operation.
	//
	// This endpoint creates a message reaction using lower case emoji names.
	//
	// POST /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions
	CreateChatReaction(ctx context.Context, req *CommentCreateChatReaction, params CreateChatReactionParams) (CreateChatReactionRes, error)
	// CreateDirectMessageChatChannel implements createDirectMessageChatChannel operation.
	//
	// This endpoint creates a new Direct Message between up to 15 users. If a Direct Message between those
	// users already exists it returns it.
	//
	// POST /api/v3/workspaces/{workspace_id}/chat/channels/direct_message
	CreateDirectMessageChatChannel(ctx context.Context, req *ChatCreateDirectMessageChatChannel, params CreateDirectMessageChatChannelParams) (CreateDirectMessageChatChannelRes, error)
	// CreateDocPublic implements createDocPublic operation.
	//
	// Create a new Doc.
	//
	// POST /api/v3/workspaces/{workspace_id}/docs
	CreateDocPublic(ctx context.Context, req *PublicDocsCreateDocOptionsDto, params CreateDocPublicParams) (*PublicDocsDocDto, error)
	// CreateLocationChatChannel implements createLocationChatChannel operation.
	//
	// This endpoint creates a Channel on a Space, Folder, or List. When a Channel already exists on the
	// requested location, it returns it.
	//
	// POST /api/v3/workspaces/{workspace_id}/chat/channels/location
	CreateLocationChatChannel(ctx context.Context, req *ChatCreateLocationChatChannel, params CreateLocationChatChannelParams) (CreateLocationChatChannelRes, error)
	// CreatePagePublic implements createPagePublic operation.
	//
	// Create a page in a Doc.
	//
	// POST /api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages
	CreatePagePublic(ctx context.Context, req *PublicDocsPublicCreatePageOptionsDto, params CreatePagePublicParams) (*PublicDocsPageV3Dto, error)
	// CreateReplyMessage implements createReplyMessage operation.
	//
	// This endpoint creates a reply message.
	//
	// POST /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/replies
	CreateReplyMessage(ctx context.Context, req *CommentCreateChatMessage, params CreateReplyMessageParams) (CreateReplyMessageRes, error)
	// DeleteChatChannel implements deleteChatChannel operation.
	//
	// This endpoint deletes a Channel. Applies to Channels tied to a Space, Folder, or List or not tied to
	// locations.
	//
	// DELETE /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}
	DeleteChatChannel(ctx context.Context, params DeleteChatChannelParams) (DeleteChatChannelRes, error)
	// DeleteChatMessage implements deleteChatMessage operation.
	//
	// This endpoint deletes a message.
	//
	// DELETE /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}
	DeleteChatMessage(ctx context.Context, params DeleteChatMessageParams) (DeleteChatMessageRes, error)
	// DeleteChatReaction implements deleteChatReaction operation.
	//
	// This endpoint deletes a message reaction.
	//
	// DELETE /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions/{reaction}
	DeleteChatReaction(ctx context.Context, params DeleteChatReactionParams) (DeleteChatReactionRes, error)
	// EditPagePublic implements editPagePublic operation.
	//
	// Edit a page in a Doc.
	//
	// PUT /api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages/{page_id}
	EditPagePublic(ctx context.Context, req *PublicDocsPublicEditPageOptionsDto, params EditPagePublicParams) (jx.Raw, error)
	// GetChatChannel implements getChatChannel operation.
	//
	// This endpoint retrieves a specific Channel given its ID.
	//
	// GET /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}
	GetChatChannel(ctx context.Context, params GetChatChannelParams) (GetChatChannelRes, error)
	// GetChatChannelFollowers implements getChatChannelFollowers operation.
	//
	// This endpoint retrieves followers of a specific Channel given its ID.
	//
	// GET /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/followers
	GetChatChannelFollowers(ctx context.Context, params GetChatChannelFollowersParams) (GetChatChannelFollowersRes, error)
	// GetChatChannelMembers implements getChatChannelMembers operation.
	//
	// This endpoint retrieves members of a specific Channel given its ID.
	//
	// GET /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/members
	GetChatChannelMembers(ctx context.Context, params GetChatChannelMembersParams) (GetChatChannelMembersRes, error)
	// GetChatChannels implements getChatChannels operation.
	//
	// This endpoint retrieves the Channels in a Workspace.
	//
	// GET /api/v3/workspaces/{workspace_id}/chat/channels
	GetChatChannels(ctx context.Context, params GetChatChannelsParams) (GetChatChannelsRes, error)
	// GetChatMessageReactions implements getChatMessageReactions operation.
	//
	// This endpoint retrieves the reactions to a message.
	//
	// GET /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions
	GetChatMessageReactions(ctx context.Context, params GetChatMessageReactionsParams) (GetChatMessageReactionsRes, error)
	// GetChatMessageReplies implements getChatMessageReplies operation.
	//
	// This endpoint retrieves the replies to a message.
	//
	// GET /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/replies
	GetChatMessageReplies(ctx context.Context, params GetChatMessageRepliesParams) (GetChatMessageRepliesRes, error)
	// GetChatMessageTaggedUsers implements getChatMessageTaggedUsers operation.
	//
	// This endpoint retrieves tagged users for a message.
	//
	// GET /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/tagged_users
	GetChatMessageTaggedUsers(ctx context.Context, params GetChatMessageTaggedUsersParams) (GetChatMessageTaggedUsersRes, error)
	// GetChatMessages implements getChatMessages operation.
	//
	// This endpoint retrieves messages for a specified Channel.
	//
	// GET /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/messages
	GetChatMessages(ctx context.Context, params GetChatMessagesParams) (GetChatMessagesRes, error)
	// GetDocPageListingPublic implements getDocPageListingPublic operation.
	//
	// View the PageListing for a Doc.
	//
	// GET /api/v3/workspaces/{workspace_id}/docs/{doc_id}/page_listing
	GetDocPageListingPublic(ctx context.Context, params GetDocPageListingPublicParams) (GetDocPageListingPublicRes, error)
	// GetDocPagesPublic implements getDocPagesPublic operation.
	//
	// View the pages belonging to a Doc.
	//
	// GET /api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages
	GetDocPagesPublic(ctx context.Context, params GetDocPagesPublicParams) (PublicDocsGetDocPagesPublic200Response, error)
	// GetDocPublic implements getDocPublic operation.
	//
	// View information about a Doc.
	//
	// GET /api/v3/workspaces/{workspace_id}/docs/{doc_id}
	GetDocPublic(ctx context.Context, params GetDocPublicParams) (GetDocPublicRes, error)
	// GetPagePublic implements getPagePublic operation.
	//
	// View the information about a page in a Doc. Due to markdown format limitations, some content
	// elements [will not be displayed exactly as they appear in ClickUp].
	//
	// [will not be displayed exactly as they appear in ClickUp]: doc:docsimportexportlimitations/
	//
	// GET /api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages/{page_id}
	GetPagePublic(ctx context.Context, params GetPagePublicParams) (GetPagePublicRes, error)
	// GetParentEntityAttachments implements getParentEntityAttachments operation.
	//
	// Return a list of attachments for the specified entity, including a task or File type Custom Field.
	//
	// GET /api/v3/workspaces/{workspace_id}/{entity_type}/{entity_id}/attachments
	GetParentEntityAttachments(ctx context.Context, params GetParentEntityAttachmentsParams) (GetParentEntityAttachmentsRes, error)
	// GetSubtypes implements getSubtypes operation.
	//
	// Get the ID of each post subtype (Announcement, Discussion, Idea, and Update) for your Workspace, to
	// use when [sending a message] with `type: post`. Subtype IDs are unique to each Workspace.
	//
	// [sending a message]: https://developer.clickup.com/reference/createchatmessage
	//
	// GET /api/v3/workspaces/{workspace_id}/comments/types/{comment_type}/subtypes
	GetSubtypes(ctx context.Context, params GetSubtypesParams) (jx.Raw, error)
	// MoveTask implements moveTask operation.
	//
	// Move a task to a new List. For Tasks in Multiple Lists, this endpoint only moves the task to a new
	// home List.
	//
	// [Learn more] about the options available when moving a task to a new List.
	//
	// [Learn more]: doc:move-a-task-to-a-new-list
	//
	// PUT /api/v3/workspaces/{workspace_id}/tasks/{task_id}/home_list/{list_id}
	MoveTask(ctx context.Context, req *TaskMoveTaskBodyParamsDto, params MoveTaskParams) (MoveTaskRes, error)
	// PatchChatMessage implements patchChatMessage operation.
	//
	// This endpoint updates a message.
	//
	// PATCH /api/v3/workspaces/{workspace_id}/chat/messages/{message_id}
	PatchChatMessage(ctx context.Context, req *CommentPatchChatMessage, params PatchChatMessageParams) (PatchChatMessageRes, error)
	// PostEntityAttachment implements postEntityAttachment operation.
	//
	// Upload an attachment to a task or to a file type Custom Field. Once a file has been uploaded to a
	// `custom_fields` entity, use [Set Custom Field Value] to associate the uploaded file with a task. To
	// retrieve the ID of a Custom Field, you can use [Get List Custom Fields] or [Get task].
	//
	// [Set Custom Field Value]: ref:SetCustomFieldValue
	// [Get List Custom Fields]: red:GetAccessibleCustomFields
	// [Get task]: ref:GetTask
	//
	// POST /api/v3/workspaces/{workspace_id}/{entity_type}/{entity_id}/attachments
	PostEntityAttachment(ctx context.Context, req *AttachmentsPublicPostAttachmentBodyParamsDtoMultipart, params PostEntityAttachmentParams) (PostEntityAttachmentRes, error)
	// PublicPatchAcl implements publicPatchAcl operation.
	//
	// Update the privacy and access settings of an object or location in the Workspace. Note that sharing
	// an item may incur charges.
	//
	// PATCH /api/v3/workspaces/{workspace_id}/{object_type}/{object_id}/acls
	PublicPatchAcl(ctx context.Context, req *UserPatchAclApiRequest, params PublicPatchAclParams) (jx.Raw, error)
	// QueryAuditLog implements queryAuditLog operation.
	//
	// Create Workspace-level audit logs. Only the Workspace owner can create audit logs. Note: This
	// endpoint is only available to Workspaces on our [Enterprise Plan].
	//
	// [Enterprise Plan]: https://clickup.com/pricing
	//
	// POST /api/v3/workspaces/{workspace_id}/auditlogs
	QueryAuditLog(ctx context.Context, req *AutoAuditlogAuditLogQueryRequest, params QueryAuditLogParams) (jx.Raw, error)
	// ReplaceTimeEstimatesByUser implements replaceTimeEstimatesByUser operation.
	//
	// Replaces all time estimates for a task with the provided time estimates. Any existing time estimates
	// not included in the request will be removed.
	//
	// Assignees must be currently assigned to the task, or use `assignee: unassigned` to set a time
	// estimates for unassigned work.
	//
	// You can set up to 10 estimates per request.
	//
	// Note: This endpoint is only available on our Business Plan or above.
	//
	// PUT /api/v3/workspaces/{workspace_id}/tasks/{task_id}/time_estimates_by_user
	ReplaceTimeEstimatesByUser(ctx context.Context, req TaskPublicApiTaskControllerReplaceTimeEstimatesByUserRequest, params ReplaceTimeEstimatesByUserParams) (ReplaceTimeEstimatesByUserRes, error)
	// SearchDocsPublic implements searchDocsPublic operation.
	//
	// View the Docs in your Workspace. You can only view information of Docs you can access.
	//
	// GET /api/v3/workspaces/{workspace_id}/docs
	SearchDocsPublic(ctx context.Context, params SearchDocsPublicParams) (*PublicDocsDocsSearchResultDto, error)
	// UpdateChatChannel implements updateChatChannel operation.
	//
	// This endpoint updates a single Channel.
	//
	// PATCH /api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}
	UpdateChatChannel(ctx context.Context, req *ChatUpdateChatChannel, params UpdateChatChannelParams) (UpdateChatChannelRes, error)
	// UpdateTimeEstimatesByUser implements updateTimeEstimatesByUser operation.
	//
	// Replace the time estimates on a task for specified assignees.
	//
	// Assignees must be currently assigned to the task, or use `assignee: unassigned` to set a time
	// estimates for unassigned work.
	//
	// You can set up to 10 estimates per request.
	//
	// Note: This endpoint is only available on our Business Plan or above.
	//
	// PATCH /api/v3/workspaces/{workspace_id}/tasks/{task_id}/time_estimates_by_user
	UpdateTimeEstimatesByUser(ctx context.Context, req TaskPublicApiTaskControllerUpdateTimeEstimatesByUserRequest, params UpdateTimeEstimatesByUserParams) (UpdateTimeEstimatesByUserRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
