// Code generated by ogen, DO NOT EDIT.

package clickupv3

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateChatChannelOperation              OperationName = "CreateChatChannel"
	CreateChatMessageOperation              OperationName = "CreateChatMessage"
	CreateChatReactionOperation             OperationName = "CreateChatReaction"
	CreateDirectMessageChatChannelOperation OperationName = "CreateDirectMessageChatChannel"
	CreateDocPublicOperation                OperationName = "CreateDocPublic"
	CreateLocationChatChannelOperation      OperationName = "CreateLocationChatChannel"
	CreatePagePublicOperation               OperationName = "CreatePagePublic"
	CreateReplyMessageOperation             OperationName = "CreateReplyMessage"
	DeleteChatChannelOperation              OperationName = "DeleteChatChannel"
	DeleteChatMessageOperation              OperationName = "DeleteChatMessage"
	DeleteChatReactionOperation             OperationName = "DeleteChatReaction"
	EditPagePublicOperation                 OperationName = "EditPagePublic"
	GetChatChannelOperation                 OperationName = "GetChatChannel"
	GetChatChannelFollowersOperation        OperationName = "GetChatChannelFollowers"
	GetChatChannelMembersOperation          OperationName = "GetChatChannelMembers"
	GetChatChannelsOperation                OperationName = "GetChatChannels"
	GetChatMessageReactionsOperation        OperationName = "GetChatMessageReactions"
	GetChatMessageRepliesOperation          OperationName = "GetChatMessageReplies"
	GetChatMessageTaggedUsersOperation      OperationName = "GetChatMessageTaggedUsers"
	GetChatMessagesOperation                OperationName = "GetChatMessages"
	GetDocPageListingPublicOperation        OperationName = "GetDocPageListingPublic"
	GetDocPagesPublicOperation              OperationName = "GetDocPagesPublic"
	GetDocPublicOperation                   OperationName = "GetDocPublic"
	GetPagePublicOperation                  OperationName = "GetPagePublic"
	GetParentEntityAttachmentsOperation     OperationName = "GetParentEntityAttachments"
	GetSubtypesOperation                    OperationName = "GetSubtypes"
	MoveTaskOperation                       OperationName = "MoveTask"
	PatchChatMessageOperation               OperationName = "PatchChatMessage"
	PostEntityAttachmentOperation           OperationName = "PostEntityAttachment"
	PublicPatchAclOperation                 OperationName = "PublicPatchAcl"
	QueryAuditLogOperation                  OperationName = "QueryAuditLog"
	ReplaceTimeEstimatesByUserOperation     OperationName = "ReplaceTimeEstimatesByUser"
	SearchDocsPublicOperation               OperationName = "SearchDocsPublic"
	UpdateChatChannelOperation              OperationName = "UpdateChatChannel"
	UpdateTimeEstimatesByUserOperation      OperationName = "UpdateTimeEstimatesByUser"
)
