// Code generated by ogen, DO NOT EDIT.
package clickupv3

type CreateChatChannelRes interface {
	createChatChannelRes()
}

type CreateChatMessageRes interface {
	createChatMessageRes()
}

type CreateChatReactionRes interface {
	createChatReactionRes()
}

type CreateDirectMessageChatChannelRes interface {
	createDirectMessageChatChannelRes()
}

type CreateLocationChatChannelRes interface {
	createLocationChatChannelRes()
}

type CreateReplyMessageRes interface {
	createReplyMessageRes()
}

type DeleteChatChannelRes interface {
	deleteChatChannelRes()
}

type DeleteChatMessageRes interface {
	deleteChatMessageRes()
}

type DeleteChatReactionRes interface {
	deleteChatReactionRes()
}

type GetChatChannelFollowersRes interface {
	getChatChannelFollowersRes()
}

type GetChatChannelMembersRes interface {
	getChatChannelMembersRes()
}

type GetChatChannelRes interface {
	getChatChannelRes()
}

type GetChatChannelsRes interface {
	getChatChannelsRes()
}

type GetChatMessageReactionsRes interface {
	getChatMessageReactionsRes()
}

type GetChatMessageRepliesRes interface {
	getChatMessageRepliesRes()
}

type GetChatMessageTaggedUsersRes interface {
	getChatMessageTaggedUsersRes()
}

type GetChatMessagesRes interface {
	getChatMessagesRes()
}

type GetDocPageListingPublicRes interface {
	getDocPageListingPublicRes()
}

type GetDocPublicRes interface {
	getDocPublicRes()
}

type GetPagePublicRes interface {
	getPagePublicRes()
}

type GetParentEntityAttachmentsRes interface {
	getParentEntityAttachmentsRes()
}

type MoveTaskRes interface {
	moveTaskRes()
}

type PatchChatMessageRes interface {
	patchChatMessageRes()
}

type PostEntityAttachmentRes interface {
	postEntityAttachmentRes()
}

type ReplaceTimeEstimatesByUserRes interface {
	replaceTimeEstimatesByUserRes()
}

type UpdateChatChannelRes interface {
	updateChatChannelRes()
}

type UpdateTimeEstimatesByUserRes interface {
	updateTimeEstimatesByUserRes()
}
