// Code generated by ogen, DO NOT EDIT.

package clickupv3

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAuthHeader handles authHeader security.
	HandleAuthHeader(ctx context.Context, operationName OperationName, t AuthHeader) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesAuthHeader is a private map storing roles per operation.
var operationRolesAuthHeader = map[string][]string{
	CreateChatChannelOperation:              {},
	CreateChatMessageOperation:              {},
	CreateChatReactionOperation:             {},
	CreateDirectMessageChatChannelOperation: {},
	CreateDocPublicOperation:                {},
	CreateLocationChatChannelOperation:      {},
	CreatePagePublicOperation:               {},
	CreateReplyMessageOperation:             {},
	DeleteChatChannelOperation:              {},
	DeleteChatMessageOperation:              {},
	DeleteChatReactionOperation:             {},
	EditPagePublicOperation:                 {},
	GetChatChannelOperation:                 {},
	GetChatChannelFollowersOperation:        {},
	GetChatChannelMembersOperation:          {},
	GetChatChannelsOperation:                {},
	GetChatMessageReactionsOperation:        {},
	GetChatMessageRepliesOperation:          {},
	GetChatMessageTaggedUsersOperation:      {},
	GetChatMessagesOperation:                {},
	GetDocPageListingPublicOperation:        {},
	GetDocPagesPublicOperation:              {},
	GetDocPublicOperation:                   {},
	GetPagePublicOperation:                  {},
	GetParentEntityAttachmentsOperation:     {},
	GetSubtypesOperation:                    {},
	MoveTaskOperation:                       {},
	PatchChatMessageOperation:               {},
	PostEntityAttachmentOperation:           {},
	PublicPatchAclOperation:                 {},
	QueryAuditLogOperation:                  {},
	ReplaceTimeEstimatesByUserOperation:     {},
	SearchDocsPublicOperation:               {},
	UpdateChatChannelOperation:              {},
	UpdateTimeEstimatesByUserOperation:      {},
}

// GetRolesForAuthHeader returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAuthHeader(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAuthHeader(operation string) []string {
	roles, ok := operationRolesAuthHeader[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityAuthHeader(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t AuthHeader
	const parameterName = "Authorization"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesAuthHeader[operationName]
	rctx, err := s.sec.HandleAuthHeader(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AuthHeader provides authHeader security value.
	AuthHeader(ctx context.Context, operationName OperationName) (AuthHeader, error)
}

func (s *Client) securityAuthHeader(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AuthHeader(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"AuthHeader\"")
	}
	req.Header.Set("Authorization", t.APIKey)
	return nil
}
