// Code generated by tools/generate_datasources.py DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

// dataSourceFactories returns all ClickUp data sources implemented by this provider.
var dataSourceFactories = []func() datasource.DataSource{}
