// Code generated by tools/generate_datasources.py DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	datasource_chat_channel "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_chat_channel"
	datasource_chat_channel_followers "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_chat_channel_followers"
	datasource_chat_channel_members "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_chat_channel_members"
	datasource_chat_channels "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_chat_channels"
	datasource_chat_message_reactions "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_chat_message_reactions"
	datasource_chat_message_replies "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_chat_message_replies"
	datasource_chat_message_tagged_users "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_chat_message_tagged_users"
	datasource_chat_messages "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_chat_messages"
	datasource_doc "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_doc"
	datasource_doc_page_listing "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_doc_page_listing"
	datasource_doc_pages "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_doc_pages"
	datasource_docs "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_docs"
	datasource_page "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_page"
	datasource_parent_entity_attachments "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/datasource_parent_entity_attachments"
)

// dataSourceFactories returns all ClickUp data sources implemented by this provider.
var dataSourceFactories = []func() datasource.DataSource{
	newChatChannelDataSource,
	newChatChannelFollowersDataSource,
	newChatChannelMembersDataSource,
	newChatChannelsDataSource,
	newChatMessageReactionsDataSource,
	newChatMessageRepliesDataSource,
	newChatMessageTaggedUsersDataSource,
	newChatMessagesDataSource,
	newDocDataSource,
	newDocPageListingDataSource,
	newDocPagesDataSource,
	newDocsDataSource,
	newPageDataSource,
	newParentEntityAttachmentsDataSource,
}

func newChatChannelDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "chat_channel",
		path:       "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}",
		schemaFunc: datasource_chat_channel.ChatChannelDataSourceSchema,
	}
}
func newChatChannelFollowersDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "chat_channel_followers",
		path:       "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/followers",
		schemaFunc: datasource_chat_channel_followers.ChatChannelFollowersDataSourceSchema,
	}
}
func newChatChannelMembersDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "chat_channel_members",
		path:       "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/members",
		schemaFunc: datasource_chat_channel_members.ChatChannelMembersDataSourceSchema,
	}
}
func newChatChannelsDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "chat_channels",
		path:       "/api/v3/workspaces/{workspace_id}/chat/channels",
		schemaFunc: datasource_chat_channels.ChatChannelsDataSourceSchema,
	}
}
func newChatMessageReactionsDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "chat_message_reactions",
		path:       "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/reactions",
		schemaFunc: datasource_chat_message_reactions.ChatMessageReactionsDataSourceSchema,
	}
}
func newChatMessageRepliesDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "chat_message_replies",
		path:       "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/replies",
		schemaFunc: datasource_chat_message_replies.ChatMessageRepliesDataSourceSchema,
	}
}
func newChatMessageTaggedUsersDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "chat_message_tagged_users",
		path:       "/api/v3/workspaces/{workspace_id}/chat/messages/{message_id}/tagged_users",
		schemaFunc: datasource_chat_message_tagged_users.ChatMessageTaggedUsersDataSourceSchema,
	}
}
func newChatMessagesDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "chat_messages",
		path:       "/api/v3/workspaces/{workspace_id}/chat/channels/{channel_id}/messages",
		schemaFunc: datasource_chat_messages.ChatMessagesDataSourceSchema,
	}
}
func newDocDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "doc",
		path:       "/api/v3/workspaces/{workspace_id}/docs/{doc_id}",
		schemaFunc: datasource_doc.DocDataSourceSchema,
	}
}
func newDocPageListingDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "doc_page_listing",
		path:       "/api/v3/workspaces/{workspace_id}/docs/{doc_id}/page_listing",
		schemaFunc: datasource_doc_page_listing.DocPageListingDataSourceSchema,
	}
}
func newDocPagesDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "doc_pages",
		path:       "/api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages",
		schemaFunc: datasource_doc_pages.DocPagesDataSourceSchema,
	}
}
func newDocsDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "docs",
		path:       "/api/v3/workspaces/{workspace_id}/docs",
		schemaFunc: datasource_docs.DocsDataSourceSchema,
	}
}
func newPageDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "page",
		path:       "/api/v3/workspaces/{workspace_id}/docs/{doc_id}/pages/{page_id}",
		schemaFunc: datasource_page.PageDataSourceSchema,
	}
}
func newParentEntityAttachmentsDataSource() datasource.DataSource {
	return &genericDataSource{
		name:       "parent_entity_attachments",
		path:       "/api/v3/workspaces/{workspace_id}/{entity_type}/{entity_id}/attachments",
		schemaFunc: datasource_parent_entity_attachments.ParentEntityAttachmentsDataSourceSchema,
	}
}
