// Code generated by tools/generate_resources.py; DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	resource_goal "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/resource_goal"
	resource_list "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/resource_list"
	resource_space "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/resource_space"
	resource_task "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/resource_task"
)

var resourceFactories = []func() resource.Resource{
	newGoalResource,
	newListResource,
	newSpaceResource,
	newTaskResource,
}

func newGoalResource() resource.Resource {
	return &genericResource{
		name:             "goal",
		createPath:       "/v2/team/{team_id}/goal",
		readPath:         "/v2/goal/{goal_id}",
		updatePath:       "/v2/goal/{goal_id}",
		deletePath:       "/v2/goal/{goal_id}",
		updateMethod:     "put",
		createBodyFields: []string{"name", "due_date", "description", "multiple_owners", "owners", "color"},
		updateBodyFields: []string{"name", "due_date", "description", "rem_owners", "add_owners", "color"},
		schemaFunc:       resource_goal.GoalResourceSchema,
	}
}

func newListResource() resource.Resource {
	return &genericResource{
		name:             "list",
		createPath:       "/v2/folder/{folder_id}/list",
		readPath:         "/v2/list/{list_id}",
		updatePath:       "/v2/list/{list_id}",
		deletePath:       "/v2/list/{list_id}",
		updateMethod:     "put",
		createBodyFields: []string{"name", "content", "markdown_content", "due_date", "due_date_time", "priority", "assignee", "status"},
		updateBodyFields: []string{"name", "content", "markdown_content", "due_date", "due_date_time", "priority", "assignee", "status", "unset_status"},
		schemaFunc:       resource_list.ListResourceSchema,
	}
}

func newSpaceResource() resource.Resource {
	return &genericResource{
		name:             "space",
		createPath:       "/v2/team/{team_id}/space",
		readPath:         "/v2/space/{space_id}",
		updatePath:       "/v2/space/{space_id}",
		deletePath:       "/v2/space/{space_id}",
		updateMethod:     "put",
		createBodyFields: []string{"name", "multiple_assignees", "features"},
		updateBodyFields: []string{"name", "color", "private", "admin_can_manage", "multiple_assignees", "features"},
		schemaFunc:       resource_space.SpaceResourceSchema,
	}
}

func newTaskResource() resource.Resource {
	return &genericResource{
		name:             "task",
		createPath:       "/v2/list/{list_id}/task",
		readPath:         "/v2/task/{task_id}",
		updatePath:       "/v2/task/{task_id}",
		deletePath:       "/v2/task/{task_id}",
		updateMethod:     "put",
		createBodyFields: []string{"name", "description", "assignees", "archived", "group_assignees", "tags", "status", "priority", "due_date", "due_date_time", "time_estimate", "start_date", "start_date_time", "points", "notify_all", "parent", "markdown_content", "links_to", "check_required_custom_fields", "custom_fields", "custom_item_id"},
		updateBodyFields: []string{"custom_item_id", "name", "description", "markdown_content", "status", "priority", "due_date", "due_date_time", "parent", "time_estimate", "start_date", "start_date_time", "points", "assignees", "group_assignees", "watchers", "archived"},
		schemaFunc:       resource_task.TaskResourceSchema,
	}
}
