#!/usr/bin/env python3
"""Generate internal/provider/datasources.go from generator_config.yml."""

import json
from pathlib import Path

CONFIG_PATH = Path("generator_config.yml")
OUTPUT_PATH = Path("internal/provider/datasources.go")


def snake_to_camel(s: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in s.split("_") if part)


def main() -> None:
    config = json.loads(CONFIG_PATH.read_text())
    data_sources = config.get("data_sources", {})

    imports = []
    constructors = []
    factory_entries = []

    for name in sorted(data_sources):
        pkg = f"datasource_{name}"
        camel = snake_to_camel(name)
        schema_func = f"{camel}DataSourceSchema"
        path = data_sources[name]["read"]["path"]
        imports.append(f'\t{pkg} "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/{pkg}"')
        constructors.append(
            f"""func new{camel}DataSource() datasource.DataSource {{
\treturn &genericDataSource{{
\t\tname:       {json.dumps(name)},
\t\tpath:       {json.dumps(path)},
\t\tschemaFunc: {pkg}.{schema_func},
\t}}
}}"""
        )
        factory_entries.append(f"\tnew{camel}DataSource,")

    content = f"""// Code generated by tools/generate_datasources.py DO NOT EDIT.

package provider

import (
\t"github.com/hashicorp/terraform-plugin-framework/datasource"
{chr(10).join(imports)}
)

// dataSourceFactories returns all ClickUp data sources implemented by this provider.
var dataSourceFactories = []func() datasource.DataSource{{
{chr(10).join(factory_entries)}
}}

{chr(10).join(constructors)}
"""

    OUTPUT_PATH.write_text(content)
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
