#!/usr/bin/env python3
"""Generate internal/provider/resources.go from generator_config.yml and the prepared spec."""

import json
import re
from pathlib import Path

CONFIG_PATH = Path("generator_config.yml")
SPEC_PATH = Path("ClickUp_PUBLIC_API_V2.prepared.json")
OUTPUT_PATH = Path("internal/provider/resources.go")


def snake_to_pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_") if part)


def find_operation(spec: dict, path: str, method: str) -> dict | None:
    item = spec.get("paths", {}).get(path, {})
    return item.get(method)


def request_body_properties(op: dict | None) -> list[str]:
    if not op:
        return []
    schema = (
        op.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema", {})
    )
    return list(schema.get("properties", {}).keys())


def main() -> None:
    config = json.loads(CONFIG_PATH.read_text())
    spec = json.loads(SPEC_PATH.read_text())

    resources = config.get("resources", {})

    lines = [
        "// Code generated by tools/generate_resources.py; DO NOT EDIT.",
        "",
        "package provider",
        "",
        "import (",
        '\t"github.com/hashicorp/terraform-plugin-framework/resource"',
        "",
    ]
    for name in sorted(resources):
        if not Path(f"internal/provider/generated/resource_{name}").exists():
            continue
        pkg = snake_to_pascal(name)
        lines.append(f'\tresource_{name} "github.com/rixlhq/terraform-provider-clickup/internal/provider/generated/resource_{name}"')
    lines.append(")")
    lines.append("")

    lines.append("var resourceFactories = []func() resource.Resource{")
    for name in sorted(resources):
        if not Path(f"internal/provider/generated/resource_{name}").exists():
            continue
        pascal = snake_to_pascal(name)
        lines.append(f"\tnew{pascal}Resource,")
    lines.append("}")
    lines.append("")

    for name, cfg in sorted(resources.items()):
        if not Path(f"internal/provider/generated/resource_{name}").exists():
            continue
        pascal = snake_to_pascal(name)
        create = cfg["create"]
        read = cfg["read"]
        update = cfg["update"]
        delete = cfg["delete"]

        create_op = find_operation(spec, create["path"], create["method"])
        update_op = find_operation(spec, update["path"], update["method"])
        create_body = request_body_properties(create_op)
        update_body = request_body_properties(update_op)

        lines.append(f"func new{pascal}Resource() resource.Resource {{")
        lines.append("\treturn &genericResource{")
        lines.append(f'\t\tname:             "{name}",')
        lines.append(f'\t\tcreatePath:       "{create["path"]}",')
        lines.append(f'\t\treadPath:         "{read["path"]}",')
        lines.append(f'\t\tupdatePath:       "{update["path"]}",')
        lines.append(f'\t\tdeletePath:       "{delete["path"]}",')
        lines.append(f'\t\tupdateMethod:     "{update["method"]}",')
        def go_string_slice(vals: list[str]) -> str:
            quoted = [f'"{v}"' for v in vals]
            return f"[]string{{{', '.join(quoted)}}}"

        lines.append(f"\t\tcreateBodyFields: {go_string_slice(create_body)},")
        lines.append(f"\t\tupdateBodyFields: {go_string_slice(update_body)},")
        lines.append(f"\t\tschemaFunc:       resource_{name}.{pascal}ResourceSchema,")
        lines.append("\t}")
        lines.append("}")
        lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
